jetzig-framework/jetzig

.github/workflows/CI.yml
=> Not running on pull requests

cli/cli.zig, cli/commands/init.zig, cli/commands/update.zig, cli/util.zig
Automatically update to latest version of Jetzig with `jetzig update`.
=> Add update command to CLI tool

src/GenerateRoutes.zig
Previous fix did not work, `@import` expects forward slashes so escaping backslashes doesn't help. Replace `\` with `/` instead.
=> Fix Windows paths again

src/jetzig/http/Headers.zig
Bugfix to resolve issue with undefined behaviour when calling `getFirstValue` - first header would always be returned. Add regression test.
=> Fix Headers.getFirstValue

cli/commands/server.zig
SORRY!!!! I made some dumb mistakes. Welp, here's a commit to fix all of that!
=> Cli: Fix bad code

README.md, demo/src/app/views/session.zig, demo/src/app/views/session/index.zmpl, src/jetzig/Environment.zig, src/jetzig/http/Session.zig, src/jetzig/util.zig, src/tests.zig
Use a new secure-random nonce for each session encryption.
Many thanks to @Trundle for writing [this gist](https://gist.github.com/Trundle/76c0d8f80999617f4d8373c03f86391a) highlighting the severity of this issue.
=> Fix session nonce re-use

build.zig.zon, demo/src/app/views/cache.zig, demo/src/app/views/cache/index.zmpl, demo/src/app/views/cache/post.zmpl, demo/src/app/views/kvstore.zig, demo/src/app/views/kvstore/index.zmpl, demo/src/main.zig, src/jetzig.zig, src/jetzig/App.zig, src/jetzig/http/Query.zig, src/jetzig/http/Request.zig, src/jetzig/http/Server.zig, src/jetzig/jobs/Job.zig, src/jetzig/jobs/Pool.zig, src/jetzig/jobs/Worker.zig, src/jetzig/kv.zig, src/jetzig/kv/Store.zig, src/jetzig/views/Route.zig
Provide configuration for JetKV backend (memory or file allocator).
=> Formalise JetKV interface for store, cache, jobs

build.zig.zon
MasterQ32 changed his github name
=> Fixed zigargs reference

build.zig, cli/cli.zig, cli/commands/routes.zig, demo/src/main.zig, src/Routes.zig, src/jetzig.zig, src/jetzig/App.zig, src/jetzig/colors.zig, src/jetzig/loggers/LogQueue.zig, src/jetzig/testing/App.zig, src/jetzig/util.zig, src/jetzig/views/Route.zig, src/routes.zig
Output all current routes. Invokes `zig build jetzig:routes`.
=> Add `jetzig routes` command

build.zig.zon, cli/build.zig.zon, src/commands/database.zig
Use the same environment setup as the main Jetzig app when running database CLI commands.
=> Fix database CLI environment variables config

build.zig.zon, cli/build.zig.zon, src/commands/database.zig
Fix missing optional database name type when reading from config
=> Fix admin database schema detection

build.zig.zon
update smtp_client (merged tls PR)
=> update pg.zig dep (out of bound fix)

build.zig.zon, cli/build.zig.zon
Reflect foreign keys, fix pk/fk serial type inference, add missing numeric types.
=> Schema reflection improvements

build.zig.zon, cli/build.zig.zon, src/Routes.zig, src/jetzig/Environment.zig, src/jetzig/http/params.zig, src/jetzig/middleware/AntiCsrfMiddleware.zig
Changes to latest Zig nightly build required several minor fixes across multiple dependencies.
=> Misc. Zig updates

cli/util.zig
=> util.zig: more helpful error message when `zig` is not in path

build.zig, build.zig.zon, cli/build.zig.zon, cli/commands/generate/mailer.zig, demo/src/app/jobs/example.zig, demo/src/app/mailers/welcome.zig, demo/src/app/views/mail.zig, src/jetzig/http/Request.zig, src/jetzig/mail.zig, src/jetzig/mail/Job.zig, src/jetzig/mail/Mail.zig, src/jetzig/mail/MailParams.zig, src/jetzig/testing/App.zig
Update dependencies to match new Zig build config API for test runners, misc. fixes needed after upgrading dependencies.
=> Zig 0.14 test runner config changes

build.zig.zon, src/jetzig/debug.zig
* Removal of std.ArrayList.popOrNull
* Removal of std.mem.page_size
=> Fixes for misc. Zig nightly changes

src/jetzig/middleware/CompressionMiddleware.zig
Fixed where the error was occurring.
=> Fix compression middleware

demo/src/main.zig
=> Set same_site to correct type

.github/workflows/CI.yml, build.zig, build.zig.zon, cli/build.zig.zon, demo/Makefile, demo/compose.yml, demo/config/database.zig, demo/src/app/database/Schema.zig, src/Routes.zig, src/commands/database.zig, src/jetzig/loggers/LogQueue.zig
Various dependencies updated after changes to `std.zig.Ast` and `std.LinkedList` and other things.
=> Zig 0.15 compatibility

build.zig, build.zig.zon, src/Routes.zig, src/commands/auth.zig, src/commands/database.zig, src/jetzig.zig, src/jetzig/auth.zig, src/jetzig/config.zig, src/jetzig/database.zig, src/jetzig/kv/Store.zig, src/jetzig/middleware/CompressionMiddleware.zig, src/jetzig/testing/App.zig
See https://github.com/ziglang/zig/commit/f32a5d349d2c359a2a1f627aa70e1a7a6f6330ea
=> Use Alignment arg instead of integer

src/jetzig/middleware/HtmxMiddleware.zig
The browser caches the responses to requests initiated by htmx, thus when a page is served from the cache it may not have any layout.
This can easily be seen on https://www.jetzig.dev (tested in Firefox and Chrome):
1. Go to the documentation.
2. Click a link in the sidebar menu.
3. Close your browser tab.
4. Restore the tab (with <kbd>Ctrl</kbd><kbd>Shit</kbd><kbd>T</kbd>).
5. The page has no CSS nor menu, inspecting the source shows the root tag is a `div`.
Adding a "vary" response header as described on https://htmx.org/docs/#caching prevents this issue.
=> HtmxMiddleware: add Vary header to prevent caching issues

build.zig, build.zig.zon, cli/build.zig.zon, demo/src/app/database/migrations/2025-03-10_01-36-58_create_users.zig, demo/src/app/database/seeders/2025-03-10_01-36-58_create_users.zig, demo/src/app/views/login.zig, demo/src/app/views/login/index.zmpl, demo/src/main.zig, src/jetzig/auth.zig
Add Jetzig module to migrations/seeders to make it available for import.
=> Extend auth + demo to show sign out

demo/src/app/views/background_jobs.zig, demo/src/app/views/basic.zig, demo/src/app/views/cache.zig, demo/src/app/views/errors.zig, demo/src/app/views/format.zig, demo/src/app/views/init.zig, demo/src/app/views/mail.zig, demo/src/app/views/markdown.zig, demo/src/app/views/session.zig
To using `request` rather than `data`.
=> Updated data handling

build.zig.zon, cli/build.zig.zon, src/routes_file.zig
https://github.com/ziglang/zig/commit/9a3540d61e57535b719b32942a4bc9ac065cbeac
=> Use path relative from cwd for output file args
