- src/app/views/zmpl.manifest.zig
- src/jetzig/http/Server.zig
- src/main.zig
Current design:
User defines a custom middleware as as a struct with the following lifetime:
- init: Creates the resources that the middleware might need, you pass a pointer to the request, the signature is the following `pub fn init(request: *jetzig.http.Request) !*@This`
- beforeRequest: Handles execution before the content is rendered/processed: posible signatures `pub fn beforeRequest(request: *jetzig.http.Request) !void` or `pub fn beforeRequest(middleware: *@This(),request: *jetzig.http.Request) !void`
- afterRequest: Handles execution after the content is rendered/processed: posible signatures `pub fn afterRequest(request: *jetzig.http.Request, result: *jetzig.caches.Result) !void` or `pub fn afterRequest(middleware: *@This(),request: *jetzig.http.Request, result: …
> Middleware Branch

- demo/src/DemoMiddleware.zig
- demo/src/app/views/quotes.zig
- src/jetzig.zig
- src/jetzig/App.zig
- src/jetzig/http/Headers.zig
- src/jetzig/http/Request.zig
- src/jetzig/http/Response.zig
- src/jetzig/http/Server.zig
- src/jetzig/http/middleware.zig
- src/jetzig/views/Route.zig
Andrew overhauled std.http to avoid allocations and put control of connection + stream into hands of users. For now, do a barebones implementation to restore compatibility, later we can do keepalive and pipelining. For now, still getting decent enough performance the "slow" way.
Relevant commit: https://github.com/ziglang/zig/commit/6395ba852a88f0e0b2a2f0659f1daf9d08e90157
Commit message copied here for posterity:
> Author: Andrew Kelley <andrew@ziglang.org>
> Date:   Tue Feb 20 03:30:51 2024 -0700
> std.http.Server: rework the API entirely
> Mainly, this removes the poorly named `wait`, `send`, `finish`
> functions, which all operated on the same "Response" object, which was
> actually being used as the request.
>
> Now, it looks like this:
> 1. std.net.Server.accept() gives you a …
> std.http overhaul

- build.zig
- demo/build.zig
Offload as much work as possible into new `jetzigInit` function provided by Jetzig's `build.zig`. This means that a new Jetzig project's `build.zig` is now almost completely vanilla with the exception of two extra lines:
```zig
const jetzig = @import("jetzig");
```
```zig
try jetzig.jetzigInit(b, exe, .{});
```
> Streamline project build.zig

- src/jetzig/http/Headers.zig
- src/jetzig/http/Request.zig
Detect request format (HTML or JSON) from `content-type` header.
Previous:
- path extension (.json, .html)
- "Accept" header
- default (.UNKNOWN => .HTML)
Current:
- path extension (.json, .html)
- "Accept" header
- "Content-Type" header
- default (.UNKNOWN => .HTML)
Adjust `http.Headers` to do case-insensitive matching to conform to HTTP spec: https://www.rfc-editor.org/rfc/rfc9110.html#name-field-names
> Use content-type header if present to detect format

- build.zig
- demo/src/app/lib/example.zig
- demo/src/app/views/root.zig
- demo/src/app/views/static.zig
- src/GenerateRoutes.zig
- src/jetzig.zig
- src/jetzig/http/Server.zig
Views are copied to zig-cache, meaning that any files in `src/` are not available for `@import` by default. Copy all .zig files from `src/` into zig-cache so that relative imports work as expected. This also removes the need to specifically copy views into zig-cache as the full tree is now present.
Also fix a bug in static route fallback - remove superfluous underscore so static routes with non-matching params render default HTML/JSON content.
> Allow importing .zig files from src/ in views

- src/GenerateRoutes.zig
Use `std.zig.pstringEscape` to correctly escape a string for setting as a Zig string. This should catch any potential issue with escaping strings.
> Fix routes.zig Windows paths

- .gitignore
- build.zig
- cli/cli.zig
- cli/commands/server.zig
Runs a development server and auto-reloads when changes are detected to files.
Note that a "change" is just an mtime update, Zig does a more intelligent change detection so avoids unnecessary recompiles, so the server reloads very quickly.
> Implement `jetzig server` command

- src/jetzig.zig
- src/jetzig/App.zig
- src/jetzig/http/Server.zig
`root_path` is cruft from previous route/template matching mechanism. Caused failure when running binary in isolation: binary can now run independently without any dependency on file system other than:
```
* public/ <-- should always be separate to allow e.g. serving directly
via nginx
* static/ <-- later will be compiled into binary
```
> Remove unneeded filesystem lookup

- demo/.gitignore
MacOS generates [.DS_Store](https://superuser.com/a/757596) junk files, and usually this is included in .gitignore in most projects to avoid confusion and polluting the repository. I think this should also be in Jetzig's default .gitignore.
> Add .DS_Store to gitignore

- .github/workflows/CI.yml
CI failed silently during "Build artifacts" stage when build failed in the bash for loop causing the overall job to be successful even when it wasn't.
> Fix CI silent failure bug

- src/jetzig/http/StaticRequest.zig
Dupe resource ID before freeing Data memory.
> Fix UAF in static routes

- src/jetzig/colors.zig
Too many unknowns trying to make this work reliably on Windows so just disabling now to declutter output, we can re-enable later and do it properly.
> Disable colors on Windows

- demo/src/app/views/redirect.zig
- src/jetzig/http/Query.zig
- src/jetzig/http/Server.zig
When query param is empty, use `jetzig.data.Data.NullType` - this way the value is still non-null (i.e. can be captured) and is still a `jetzig.data.Value` so is consistent with previous implementation.
Add very weird bugfix for 404 responses.
Fix `Bad Request` response code.
> Closes #53: Add support for empty HTTP query param

- build.zig
- build.zig.zon
- cli/commands/generate.zig
- cli/commands/generate/job.zig
- cli/commands/generate/layout.zig
- cli/commands/generate/middleware.zig
- cli/commands/generate/partial.zig
- cli/commands/generate/secret.zig
- cli/commands/generate/view.zig
- demo/src/app/jobs/example.zig
- demo/src/app/jobs/iguana.zig
- demo/src/app/views/background_jobs.zig
- demo/src/app/views/kvstore.zig
- demo/src/main.zig
- src/Routes.zig
- src/jetzig.zig
- src/jetzig/App.zig
- src/jetzig/http/Request.zig
- src/jetzig/http/Server.zig
- src/jetzig/jobs.zig
- src/jetzig/jobs/Job.zig
- src/jetzig/jobs/Pool.zig
- src/jetzig/jobs/Worker.zig
- src/jetzig/loggers.zig
- src/jetzig/loggers/DevelopmentLogger.zig
- src/jetzig/loggers/JsonLogger.zig
- src/tests.zig
Use in-memory KV store (JetKV) for simple job queue.
Build script generates an array of Zig modules in `src/app/jobs/` and stores their name + run function (`run(allocator, params, logger)`).
View functions schedule jobs with arbitrary params.
Thread pool spawns a (configurable) number of workers and pops jobs from the queue, then invokes the appropriate run function.
> Background jobs

- build.zig
- build.zig.zon
- cli/commands/generate.zig
- cli/compile.zig
- demo/src/app/views/markdown/index.md.zmpl
- demo/src/app/views/quotes.zig
- demo/src/app/views/root/index.zmpl
- demo/src/main.zig
- src/GenerateMimeTypes.zig
- src/Routes.zig
- src/compile_static_routes.zig
- src/jetzig/http/Server.zig
- src/jetzig/markdown.zig
Also adds support for `.md.zmpl` templates - root node is Markdown.
> Update Zmpl, adds Markdown mode formatters

- demo/public/404.html
- demo/src/app/views/errors.zig
- demo/src/app/views/errors/index.zmpl
- src/jetzig/http/Headers.zig
- src/jetzig/http/Request.zig
- src/jetzig/http/Server.zig
Render `src/app/views/errors.zig` view (`index` action) when an unexpected error occurs. If the view does not exist, try rendering `public/404.html`, `public/500.html` (etc.), finally falling back to a standard basic HTML/JSON response.
> Custom error pages

- build.zig
Allow things like `@embedFile` to work from copied src/ directory.
> Remove check for .zig extension on copy src/

- cli/commands/generate/layout.zig
Fixed the `jetzig generate layout` command like we talked on [discord](https://discord.com/channels/1203669535488479273/1203669537246019646/1242247382679294012) to be updated with the new zmpl syntax
> Fixed the command: "jetzig generate layout" to the new zmpl syntax

- demo/src/app/views/custom/foo.zig
- demo/src/app/views/custom/foo/bar.zmpl
- demo/src/main.zig
- src/jetzig.zig
- src/jetzig/App.zig
- src/jetzig/http/Path.zig
- src/jetzig/http/Request.zig
- src/jetzig/http/Server.zig
- src/jetzig/views.zig
- src/jetzig/views/CustomRoute.zig
- src/jetzig/views/Route.zig
In `main()`:
```zig
app.route(.GET, "/custom/:id/foo/bar", @import("app/views/custom/foo.zig"), .bar);
```
Routes `GET` request with path (e.g.) `/custom/1234/foo/bar` to `bar()` defined in `src/app/views/custom/foo.zig`.
Routes with an `:id` segment expect a function with three parameters, routes without an `:id` segment expect a function with two parameters (i.e. the same as `get` vs `index`).
> Implement custom routes

- build.zig.zon
- demo/src/app/views/quotes.zig
- src/jetzig.zig
- src/jetzig/App.zig
- src/jetzig/http/Path.zig
- src/jetzig/http/Request.zig
- src/jetzig/http/Server.zig
- src/jetzig/middleware.zig
- src/jetzig/middleware/HtmxMiddleware.zig
- src/jetzig/views/Route.zig
Permit setting template during view render with `request.setTemplate()`
Permit middleware to define custom routes to static content with `pub const Routes` (implemented for something no longer needed but seems useful anyway).
Implement globbing on custom routes, `/foo/:bar*` will glob all path segments including and after `/foo/...`, e.g. `/foo/bar/baz/qux` will pass invoke the custom view function with an array of `bar`, `baz`, `qux` as first argument (instead of typical resource ID).
> Update Zmpl for template inheritance

- demo/src/app/middleware/DemoMiddleware.zig
- demo/src/app/views/301.zmpl
- demo/src/main.zig
- src/jetzig.zig
- src/jetzig/colors.zig
- src/jetzig/http.zig
- src/jetzig/http/Request.zig
- src/jetzig/http/Server.zig
- src/jetzig/http/middleware.zig
- src/jetzig/loggers/DevelopmentLogger.zig
- src/jetzig/middleware/HtmxMiddleware.zig
Allow middleware to resolve a request by calling `request.redirect` or `request.render` - after this point, the request stops processing and renders immediately.
> Middleware request resolution

- src/jetzig.zig
- src/jetzig/http/Cookies.zig
- src/jetzig/http/Request.zig
- src/jetzig/http/Session.zig
- src/jetzig/util.zig
Hello. I added the ability to specify cookie options in the jetzig config.
I added all the options specified here: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Set-Cookie.
The default set-cookie output matches the previous output if no config changes are made.
> Added cookie options

- demo/src/app/views/format.zig
- demo/src/app/views/format/get.zmpl
- demo/src/app/views/format/index.zmpl
- src/Routes.zig
- src/jetzig/App.zig
- src/jetzig/http/Server.zig
- src/jetzig/views/Route.zig
- src/routes_exe.zig
- src/test_runner.zig
Define `pub const formats` in a view to specify which formats are available. Use this to e.g. disable JSON responses.
> Implement response format constraints

- build.zig.zon
smtp_client was making a wrong local copy of
an internal buffer.
Diff between current version and this updated one.
https://github.com/karlseguin/smtp_client.zig/compare/964152ad4e19dc1d22f6def6f659c86df60e7832...48971bc919fe22d2bf6accb832b73ab53e534836
> Update the smtp_client dependency.

- src/jetzig/Environment.zig
When an environment variable configures the database name we connect to, we need to wrap the field access in a comptime check even if the `orelse` block never runs.
> Fix database launch message

- .github/workflows/CI.yml
- build.zig
- build.zig.zon
- demo/src/app/views/anti_csrf.zig
- demo/src/app/views/anti_csrf/index.zmpl
- demo/src/app/views/anti_csrf/post.zmpl
- demo/src/main.zig
- src/Routes.zig
- src/commands/routes.zig
- src/compile_static_routes.zig
- src/jetzig.zig
- src/jetzig/App.zig
- src/jetzig/TemplateContext.zig
- src/jetzig/callbacks.zig
- src/jetzig/config.zig
- src/jetzig/development_static.zig
- src/jetzig/http.zig
- src/jetzig/http/Cookies.zig
- src/jetzig/http/Headers.zig
- src/jetzig/http/Request.zig
- src/jetzig/http/Server.zig
- src/jetzig/mail/Job.zig
- src/jetzig/middleware.zig
- src/jetzig/middleware/AntiCsrfMiddleware.zig
- src/jetzig/middleware/AuthMiddleware.zig
- src/jetzig/testing/App.zig
- src/jetzig/util.zig
- src/jetzig/views/Route.zig
Add to middleware in app's `src/main.zig`:
```zig
pub const jetzig_options = struct {
pub const middleware: []const type = &.{
jetzig.middleware.AntiCsrfMiddleware,
};
};
```
CSRF token available in Zmpl templates:
```
{{context.authenticityToken()}}
```
or render a hidden form element:
```
{{context.authenticityFormElement()}}
```
The following HTML requests are rejected (403 Forbidden) if the submitted query param does not match the value stored in the encrypted session (added automatically when the token is generated for a template value):
* POST
* PUT
* PATCH
* DELETE
JSON requests are not impacted - users should either disable JSON endpoints or implement a different authentication method to protect them.
> Closes #108: Anti-CSRF middleware

- build.zig.zon
- cli/commands/generate/view.zig
- demo/src/app/views/root.zig
- demo/src/app/views/session.zig
- src/Routes.zig
- src/jetzig/http/Path.zig
- src/jetzig/http/Request.zig
- src/jetzig/http/Server.zig
- src/jetzig/views/Route.zig
Implement `/foo/1/edit` route/view.
Allow setting HTTP verb by passing e.g. `/_PATCH` as the last segment of a URL - this allows browsers to submit a `POST` request with a pseudo-HTTP verb encoded in the URL which Jetzig can translate, i.e. allowing forms to submit a `PATCH`.
> Routing updates

- build.zig.zon
Fix for coercing datetime values in where/insert/etc. params and managing optional datetimes in schema.
> JetQuery: fix datetime coercion

- cli/commands/generate/mailer.zig
When using jetzig cli to generate mailer the actual zig file was missing the imports so i added them
> Added imports to mailers

- build.zig.zon
- cli/build.zig.zon
- src/commands/routes.zig
- src/jetzig/colors.zig
- src/jetzig/http/Server.zig
- src/jetzig/loggers/DevelopmentLogger.zig
Use JetQuery's new `Repo.bindConnect()` to get a new Repo bound to a connection for each request. This significantly simplifies connection management and offloads all the connection pool
management/reconnecting/etc. to pg.zig where it belongs.
Improve development mode SQL syntax highlighting - highlight `SELECT`, `UPDATE`, `DELETE`, `INSERT` in different bolded colors for clarity.
> Per-request database connection

- src/jetzig/http/Request.zig
- src/jetzig/mail/Job.zig
Prevent breaking out of "To" recipient resolving when `name` is null - this is a valid value as we only need the `email` field to deliver an email successfully.
> Fix email recipients

- src/jetzig/middleware/HtmxMiddleware.zig
Using a target like `hx-target="next div"` will not generate an HX-Target header if the target element does not have an ID. Judging by the comments it used to be HX-Request.
> Switched HX-Target header to HX-Request in HtmxMiddleware

- cli/util.zig
This fixes a memory leak in the CLI, the message was being allocated but never deallocated anywhere.
Fixes #167
> Fix memory leak in CLI

- src/jetzig/App.zig
- src/jetzig/loggers/LogQueue.zig
I believe this change is needed due to this: https://ziglang.org/download/0.14.0/release-notes.html#Remove-Anonymous-Struct-Types-Unify-Tuples
I fixed it by declaring a non-anonymous struct type for this parameter, which allows to use it in `Thread.spawn`. I believe this is due to type coercion not being able to work in this specific case but I might be mistaken.
> Fix anonymous struct literal in log_thread spawn

- .github/workflows/CI.yml
Previous workflow uses:
* nightly Zig version which unforutnately is breaking
* workflow step that is unmaintained
This should also fix the broken [Jetzig binaries at Download page](https://www.jetzig.dev/downloads.html).
Replaces https://github.com/jetzig-framework/jetzig/pull/175
> Switches zig-setup workflow allowing building on latest stable Zig

- .github/workflows/CI.yml
- cli/commands/init.zig
- cli/compile.zig
- demo/config/database.zig
- demo/config/database_template.zig
- demo/src/app/database/Schema.zig
- demo/src/app/database/migrations/2024-08-25_13-18-52_hello.zig
- demo/src/app/database/migrations/2025-03-10_01-36-58_create_users.zig
- demo/src/app/views/login.zig
- demo/src/app/views/login/index.zmpl
- src/jetzig/auth.zig
- src/jetzig/testing/App.zig
This adds a small example for using authentication and signing in a user. This will be linked to from the jetzig.dev documentation, for how to use the authentication middleware
> Add an example for using auth for logging in

- .github/workflows/CI.yml
- build.zig.zon
Defines a consistent minimum supported Zig version, also updated CI to test against the minimum version.
This adds some form of consistency following #185 now that we are beyond stable releases.
> Defines minimum supported Zig version.

- .github/workflows/CI.yml
To avoid repetition, CI now sets up Zig as defined in `minimum_zig_version` in `build.zig.zon`.
Earlier PR failed because:
1. I was not aware that GitHub Actions does not do semver.
2. This feature is [still unreleased](https://github.com/mlugg/setup-zig/issues/16) but working.
> CI now uses minimum_zig_version as defined in build.zig.zon

- demo/src/app/views/anti_csrf/index.zmpl
- src/jetzig/http/Request.zig
- src/jetzig/http/Session.zig
- src/jetzig/testing/App.zig
Allowing overriding of default session cookie name just for general good practice. 
To override, set env var `JETZIG_SESSION_COOKIE`:
```sh
export JETZIG_SESSION_COOKIE=myapp
```
WIll update documentation if this is accepted. WIll perhaps write a documentation on Session. Can't seem to find one at https://www.jetzig.dev/documentation.html
> Overriding of default session cookie name

- demo/src/app/views/render_text.zig
- demo/src/app/views/render_text/index.zmpl
- src/jetzig/http.zig
- src/jetzig/http/Request.zig
- src/jetzig/http/Response.zig
- src/jetzig/http/Server.zig
- src/jetzig/testing.zig
Render a text string (+ status code) directly.
> Implement `request.renderText()`

- demo/src/main.zig
- src/jetzig/config.zig
- src/jetzig/http/Server.zig
Set `public_routing_path` config option to specify a request path prefix for public requests.
> Public routing path

- build.zig
Use CPU arch to detect whether to use LLVM - self-hosted compiler is not currently ready for ARM.
> Fix Linux ARM compilation

- build.zig.zon
Update Zmpl to allow passing `*ZmplValue` as an argument, i.e. this should work where the ref `foo` is any Zmpl value:
```
@partial($.foo)
```
> Zmpl partial ZmplValue

- cli/build.zig
- cli/cli.zig
- cli/commands/version.zig
Thought it would be easier to figure out the version of jetzig in my path that way. 
```sh
$ jetzig version
0.0.0+1cb27ffec8
```
The version consists of 2 components, similar to Zig's version:
* Version, taken from `build.zig.zon`, currently 0.0.0.
* Git's commit hash, using 9 characters similar to Zig and separated by `+`.
> `jetzig version` support

- cli/commands/init.zig
- cli/compile.zig
- demo/src/app/views/init.zig
- demo/src/app/views/init/index.zmpl
- demo/src/app/views/layouts/default.zmpl
New users can learn about layout from initialized project via `jetzig init` rather than having to discover it through documentation, besides it can be a better boilerplate to an actual project.
> Initialized project uses layout

- flake.lock
- flake.nix
Wanted to give jetzig a try today, but could not find a working build for nixos. So this is my attempt to fix it.
I noticed the following issues with flake.nix:
- It always uses deps.nix from main, which breaks the build when trying to build for 0.14
- It uses fetchGit without rev, which requires impure evaluation
To fix this, I made the following changes:
- The build will use the deps.nix file from the source tree that is built
- Only fetch jetzig from github if v14 is built. Otherwise it just builds from the current directory.
I also made smaller changes to try to clean up the inputs and the output packages.
With those changes, I can just run `nix shell github:jrammler/jetzig/nix-build-fixes#v14` to start a shell with jetzig.
Note that builds with both zig 0.15.1 as well as master …
> Fix nix flake build issues
